composer.json, composer.lock, html/modules/custom/odsg_migrate/src/Helpers/Outliner.php, html/modules/custom/odsg_migrate/src/Plugin/migrate/process/OdsgCleanHtml.php, html/modules/custom/odsg_ocha/src/Plugin/views/query/OdsgOchaFeed.php, html/modules/custom/odsg_ocha/src/Plugin/views/query/OdsgOchaFunding.php, html/sites/default/default.settings.php
- Move OCHA services to footer
- Bump common design base theme
- Bump Drupal core to 8.9.13
- Subtheme dependencies update
=> Deployment - 2021/01/28

composer.json, composer.lock
https://humanitarian.atlassian.net/browse/ODSG-38
Security update to ctools module
=> [ODSG-38] update ctools to 3.6.0

composer.lock, html/.gitignore, html/modules/.gitignore, html/profiles/.gitignore, html/sites/.gitignore, html/themes/.gitignore
https://humanitarian.atlassian.net/browse/OPS-7493
=> [OPS-7493] update core to 8.9.16

composer.lock, html/.gitignore, html/modules/.gitignore, html/profiles/.gitignore, html/sites/.gitignore, html/themes/.gitignore
https://humanitarian.atlassian.net/browse/OPS-7493
=> [OPS-7493] security release

composer.lock
https://humanitarian.atlassian.net/browse/OPS-7688
Note - this deployment will include upgrading to Drupal 9, so deserves some extra clicking around.
=> [OPS-7688] update core to 9.2.4

html/themes/custom/common_design_subtheme/.stylelintrc.json, html/themes/custom/common_design_subtheme/package-lock.json, html/themes/custom/common_design_subtheme/package.json
https://humanitarian.atlassian.net/browse/CD-329
=> [CD-329] update stylelint config

composer.lock
https://humanitarian.atlassian.net/browse/OPS-7780
=> [OPS-7780] update core to 9.2.6

.github/workflows/docker-build-image.yml
https://humanitarian.atlassian.net/browse/OPS-7766
to avoid: https://github.com/UN-OCHA/odsg8-site/runs/4251786250?check_suite_focus=true
=> [OPS-7766] add login to avoid too many requests error

composer.lock, symfony.lock
https://humanitarian.atlassian.net/browse/OPS-7997
Small updates to config_split, console, devel, stage_file_proxy and upgrade_status. The last required updating dependencies too.
=> [OPS-7997] update dev modules

composer.lock
https://humanitarian.atlassian.net/browse/OPS-7998
Module updates for redirect, social_auth_hid and token.
=> [OPS-7998] update contrib modules

composer.json, composer.lock, config/social_auth_hid.settings.yml, html/sites/default/default.services.yml
https://humanitarian.atlassian.net/browse/OPS-8135
=> [OPS-8135] bump social_auth_hid and small updates for other modules

composer.json, composer.lock, composer.patches.json, config/core.extension.yml, config/user_expire.settings.yml, symfony.lock
https://humanitarian.atlassian.net/browse/OPS-7459
Adds and configures user_expire with the patches mentioned in https://github.com/UN-OCHA/assessmentregistry8-site/pull/360
=> [OPS-7459] user expire

Makefile
Refs: OPS-8219
Companion to https://github.com/UN-OCHA/odsg-stack/pull/59
=> chore: update local image name

composer.json, composer.lock, composer.patches.json, config/core.extension.yml, config/seckit.settings.yml
=> chore: seckit improvements

composer.lock, symfony.lock
Refs: OPS-7520
Haven't done the update - just updated the flagged packages so the update can run this week.
=> chore: update composer package that was causing problems

composer.json, composer.lock
Refs: Periodic updates
Follow-on to https://github.com/UN-OCHA/odsg8-site/pull/117
=> chore: update ctools module

config/pathauto.pattern.announcement.yml, config/pathauto.pattern.content_path.yml, config/pathauto.pattern.pages.yml
=> fix: update pathauto config

.dockerignore, .travis.yml, composer.json, composer.lock, docker/Dockerfile, phpunit.xml, tests/content/404.content.yml, tests/content/home.content.yml, tests/docker-compose.yml, tests/settings/default.services.yml, tests/settings/services.yml, tests/settings/settings.local.php, tests/settings/settings.php, tests/settings/settings.test.php
=> tests: add failing tests

config/csp.settings.yml
=> chore: update csp config

composer.lock, html/sites/default/default.settings.php
=> Core security update

.github/workflows/composer-update.yml, .travis.yml, composer.json, composer.lock
minimum-stability to stable
Refs: updates
=> fix: pin composer version until preserve-paths is fixed and upgrade

.github/workflows/run-tests.yml
=> chore: fix access key variable

.github/workflows/run-tests.yml
=> chore: add permissions so dependabot tests pass

html/modules/custom/odsg_ocha/src/Plugin/views/query/OdsgOchaFeed.php
=> fix: include Guzzle Exception correctly

composer.lock, html/modules/custom/odsg_ocha/src/Plugin/views/query/OdsgOchaFeed.php
=> Deploy 16-08-2023 part 2

config/config_split.config_split.config_dev.yml, config/environment_indicator.switcher.dev.yml, config_dev/environment_indicator.switcher.local.yml
=> chore: update environment indicator config

docker/Dockerfile
Refs: OPS-9635
To fix https://jenkins.aws.ahconu.org/view/Updates/job/odsg-prod-updates/1291/console
=> chore: self-update composer in Dockerfile

docker/Dockerfile
=> chore: keep composer version as set in php image

composer.json, composer.lock
=> chore: remove ckeditor module

local/.env.example, local/README.md, local/install.sh
chore: update readme, example env and install to reflect most recent updates to starterkit
=> Update local stack

local/.env.example, local/docker-compose.yml, local/install.sh, local/shared/settings/services.yml, local/shared/settings/settings.local.php
=> chore: update local stack for consistency

docker/Dockerfile
=> fix: allow composer super user

.docksal/settings/settings.local.php, composer.json, composer.lock
=> [CD-533] Upgrade to CD v9.3.2

PATCHES/amazon_ses-3417090-cron-queue-14.patch, composer.json, composer.lock, composer.patches.json, config/amazon_ses.settings.yml, config/aws.profile.amazon_ses.yml, config/aws.settings.yml, config/core.extension.yml, config/mailsystem.settings.yml
=> chore: Add Amazon SES support and config to be managed via Ansible.

composer.lock
=> chore: revert to core version 10.2.7 until 10.3 is better tested

composer.lock
=> chore: revert other core packages too

config/seckit.settings.yml
=> chore: domains for google ads

config/seckit.settings.yml
=> chore: straighten csp settings

PATCHES/core_js_optimizer.patch, composer.patches.json
=> fix: js optimizer errors

PATCHES/core_js_optimizer.patch, composer.lock, composer.patches.json
IASC-799 - Js Optimization errors
=> Deploy 18-08-2024

composer.json, composer.lock
=> chore: remove unused classy theme

config/core.entity_form_display.node.announcement.default.yml, config/core.entity_form_display.node.page.default.yml, config/core.entity_form_display.node.public_page.default.yml, config/core.extension.yml, config/field.field.node.announcement.body.yml, config/field.field.node.odsg_document.body.yml, config/field.field.node.page.body.yml, config/field.field.node.page.field_sidebar.yml, config/field.field.node.public_page.body.yml
=> chore: remove allowed_formats module and handle configuration

.github/workflows/composer-update-scripts.yml
=> updates: allow scripts to run

CHANGELOG.md, composer.json, composer.lock
| Production Changes     | From  | To    | Compare                                                                 |
|------------------------|-------|-------|-------------------------------------------------------------------------|
| unocha/ocha_monitoring | 1.1.0 | 1.1.1 | [...](https://github.com/UN-OCHA/ocha_monitoring/compare/1.1.0...1.1.1) |
=> Deploy 20-03-2025

.github/workflows/composer-update.yml
=> chore: suspend updates now the site is mothballed

.github/workflows/composer-update-scripts.yml, .github/workflows/composer-update.yml
=> chore: Use the visible / editable maintainers var for PR assignment.
